version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: option-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # anonymous volume to avoid host node_modules clobber
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped